language: java
jdk:
    - oraclejdk8
services:
    - mysql
deploy:
    provider: heroku
    api-key:
        secure: $HEROKU_API_KEY
    app: haxonomy-backend
    on:
        repo: fongie/haxonomy
env:
    - SPRING_PROFILES_ACTIVE=travis
before_install:
    - chmod a+x mvnw
    - mysql -e 'DROP DATABASE IF EXISTS haxonomy;'
    - mysql -e 'CREATE DATABASE haxonomy;'
