spring:
  datasource:
    url: jdbc:mysql://localhost:3306/haxonomy?useLegacyDatetimeCode=false&characterEncoding=UTF-8
    username: root
    password: root
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update #should be none in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
---
spring:
  profiles: heroku
  server:
    port: ${PORT}
  datasource:
    url: ${CLEARDB_DATABASE_URL}&useLegacyDatetimeCode=false&characterEncoding=UTF-8
    username: ${CLEARDB_USER}
    password: ${CLEARDB_PASSWORD}
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  profiles: travis
  datasource:
    url: jdbc:mysql://localhost:3306/haxonomy?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: root
    password: ''
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
