spring:
  datasource:
    url: jdbc:mysql://localhost:3306/haxonomy?useLegacyDatetimeCode=false&characterEncoding=UTF-8
    username: root
    password: root
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: create-drop #should be none in production